version: '3'

services:
  web:
    container_name: plannerbox-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: production
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      - NODE_ENV=production
  api:
    container_name: plannerbox-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: production
    restart: always
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      - db
    command: npx nest start --watch
    environment:
      - NODE_ENV=production
  db:
    container_name: plannerbox-db
    image: postgres
    user: postgres
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
